name: lando-goodies
recipe: drupal9
config:
  webroot: web
  database: mariadb

proxy:
  mailhog:
    - "mailhog.lando-goodies.lndo.site"

services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://lando-goodies.lndo.site"
