name: lando
recipe: drupal9
config:
  webroot: web

proxy:
  mailhog:
    - "mailhog.lando.lndo.site"

services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://lando.lndo.site"
